services:
  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      - DB_HOST=postgres
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - mvnet
  
  postgres:
    image: postgres:17.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=movie_library
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d movie_library"]
      interval: 5s
    restart: unless-stopped
    networks:
      - mvnet

volumes:
  postgres_data:
    external: true

networks:
  mvnet:
    external: true
    driver: bridge