CREATE OR REPLACE FUNCTION UDPATE_UPDATED_AT()
RETURNS TRIGGER AS $$
BEGIN
    NEW.UPDATED_AT := NOW();
    RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER trigger_update_updated_at
BEFORE UPDATE ON MOVIES
FOR EACH ROW
EXECUTE FUNCTION UDPATE_UPDATED_AT();