CREATE TABLE IF NOT EXISTS MOVIES (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITLE TEXT NOT NULL,
    DIRECTOR TEXT NOT NULL,
    RELEASE_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    GENRE TEXT NOT NULL,
    DESCRIPTION TEXT,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)